version: '3.5'

services:

  adaa:
    container_name: adaa
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=development
